//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHealthCare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppointmentPayment
    {
        public int PaymentID { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<System.DateTime> Dated { get; set; }
        public Nullable<int> AppointmentID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string TransactionID { get; set; }
    }
}
