//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHealthCare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatMessage
    {
        public long ChatMessageId { get; set; }
        public Nullable<long> ChatId { get; set; }
        public string Message { get; set; }
        public Nullable<long> MessageBy { get; set; }
        public string FileName { get; set; }
        public string FilePath { get; set; }
        public Nullable<bool> IsRead { get; set; }
        public bool IsFavorite { get; set; }
        public Nullable<int> Reaction { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual Chat Chat { get; set; }
    }
}
