//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHealthCare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabTest
    {
        public int LabTestID { get; set; }
        public Nullable<int> PatientID { get; set; }
        public string TestName { get; set; }
        public string TestDate { get; set; }
        public string Report { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> UsedID { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual User User { get; set; }
    }
}
