//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHealthCare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prescription
    {
        public int PatientPrescriptionID { get; set; }
        public int MedicineID { get; set; }
        public Nullable<int> PatientID { get; set; }
        public string Reason { get; set; }
        public string Dose { get; set; }
        public string Unit { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Comments { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual Medicine Medicine { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual User User { get; set; }
    }
}
