//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHealthCare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomAllotment
    {
        public int RoomAllotmentID { get; set; }
        public Nullable<int> RoomID { get; set; }
        public Nullable<int> PatientID { get; set; }
        public Nullable<System.DateTime> Dated { get; set; }
        public Nullable<System.DateTime> DischargeDate { get; set; }
        public Nullable<int> Duration { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual Room Room { get; set; }
    }
}
